name: CI Deploy storybook

# on:
#   release:
#     types: [published, unpublished]

on:
  push:
    branches:
      - test-actions

jobs:
  build-storybook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build:storybook

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: 'storybook-static'
